[package]
name = "mmm"
description = "Mega Merge Mosaic — fast astrophotography mosaic merging/blending CLI"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "mmm"
path = "src/main.rs"

[dependencies]
mmm-core.workspace = true
anyhow.workspace = true
clap.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
